#!/bin/bash

dn="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

if [ -z "${PYTHONPATH}" ]; then
  export PYTHONPATH="$dn/src"
else
  export PYTHONPATH="$dn/src:$PYTHONPATH"
fi

"$dn/__pipenv" run python "$@"